version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    command: 'npm run server:dev'
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - './src:/app/src'
