version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    command: 'npm run server:dev'
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - './src:/app/src'
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: web-cadvisor
  #   restart: always
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker:/var/lib/docker:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #   devices:
  #     - /dev/kmsg
  #   depends_on:
  #     - web
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: web-prometheus
#     restart: always
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./prometheus:/etc/prometheus
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     ports:
#       - '9090:9090'
#   alertmanager:
#     image: prom/alertmanager:v0.23.0
#     restart: unless-stopped
#     ports:
#       - "9093:9093"
#     volumes:
#       - "./alertmanager:/config"
#       - alertmanager-data:/data
#     command: --config.file=/config/alertmanager.yml --log.level=debug --cluster.advertise-address=0.0.0.0:9093
#   discord-alerts:
#     image: benjojo/alertmanager-discord
#     container_name: discord-alerts
#     restart: unless-stopped
#     environment:
#       - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
#     ports:
#       - 9094:9094
#   grafana:
#     image: grafana/grafana:latest
#     container_name: web-grafana
#     restart: always
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./grafana/grafana.ini:/etc/grafana/grafana.ini
#       - ./grafana/provisioning:/etc/grafana/provisioning
#       - ./grafana/data:/var/lib/grafana
#     user: "1000"
#     depends_on:
#       - prometheus
#     ports:
#     # use 3000 instead
#       - "3100:3100" 

# volumes:
#   alertmanager-data:

