version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    command: 'npm run server:dev'
    ports:
      - '8080:8080'
    env_file: .env.local
    volumes:
      - './src:/app/src'
